# Generated by Django 2.0.3 on 2018-03-08 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='kafedra',
            new_name='kafedras',
        ),
        migrations.AlterField(
            model_name='student',
            name='ID',
            field=models.IntegerField(max_length=100),
        ),
    ]
